# Generated by Django 3.2.13 on 2023-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customers',
            name='accountInfo',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customers',
            name='fname',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customers',
            name='lname',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
