# Generated by Django 3.2.13 on 2023-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicerecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecords',
            name='email',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecords',
            name='password',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecords',
            name='service',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
